### PR TITLE
.Net Standard 2.0 conversion of this library

### PR DESCRIPTION
**Pull request by albertodall**
Since I use this library a lot when I'm doing demos, I thought it would be useful to have a .Net Standard version of it, so you can use it also in .NET Core projects.
I created a .Net Standard 2.0 project, because the code uses Reflection, so the minimum runtime versions required now are:
- .NET Core: 2.0 (and above)
- .NET Framework: 4.6.1 (and above)

### CODE REVIEW

**Comment by caleb-vear** [comment]
@albertodall, this sounds useful thanks for putting it together.  I'll try and take a look at it over the weekend.

**Comment by albertodall** [comment]
@caleb-vear Great! Let me know.

**Comment by albertodall** [comment]
Hello @caleb-vear. Any news about this PR?

**Comment by caleb-vear** [comment]
@albertodall sorry for the delay in looking at this.  Unfortunately things did not go to plan that weekend and I ended up spending a bunch of time at hospital looking after a family member.  Thankfully everyone is okay now but it was a hectic few weeks.  I had a lot of other work to catchup on after that and sadly didn't have a chance to look at this again until now.

I've merged it all now and published the new version to NuGet.

Thanks again for contributing to the project.

**Comment by albertodall** [comment]
Hello @caleb-vear , I'm happy that everthing ended up well!
Health is the most important thing, we know; I'm telling you that directly from a COVID-19 red zone in Italy! :-)
Glad for being helpful in contributing to your project. Now I can showcase it again during my training courses. ;-)

**Comment by caleb-vear** [comment]
@albertodall best of luck avoiding COVID-19.  From the news reports it seems reasonably bad over there.

**Pull request merged**
